import { steps } from "framer-motion";
import {
  Calendar,
  User,
  ShoppingCart,
  LayoutTemplate,
  MessageCircle,
  Zap,
  CreditCard,
  Globe,
  Smartphone,
} from "lucide-react";

export const featuresData = [
  {
    slug: "shop-builder",
    title: "Shop Builder",
    description:
      "Create beautiful online stores with our drag-and-drop Shop Builder. No coding required - launch your ecommerce business in minutes.",
    icon: ShoppingCart,
    color: "bg-blue-50",
    detailedDescription:
      "Our Shop Builder provides everything you need to create, customize, and grow your online store:",
    features: [
      "Drag-and-drop store designer",
      "100+ professionally designed templates",
      "Integrated payment processing",
      "Inventory management system",
      "Mobile-optimized storefronts",
    ],
    cta: "Start selling online today",
    steps: [
      "Choose your perfect template",
      "Customize with your branding",
      "Add your products",
      "Set up payments",
      "Launch your store",
    ],
    benefits: [
      "Increase sales with beautiful store designs",
      "Save time with intuitive tools",
      "Reach customers on any device",
      "24/7 customer support",
    ],
    shortDescription: "Complete ecommerce solution for businesses of all sizes",
    tags: ["Ecommerce", "Online Store", "React"],
    results: [
      "85% faster store setup",
      "40% higher conversion rates",
      "4.9/5 user satisfaction",
    ],
    faqs: [
      {
        question: "Do I need coding skills to use Shop Builder?",
        answer:
          "No, our drag-and-drop interface makes it easy for anyone to create a professional online store.",
        isOpen: false,
      },
      {
        question: "Can I use my own domain?",
        answer:
          "Yes, you can connect your existing domain or purchase a new one through our platform.",
        isOpen: false,
      },
    ],
    pricingPlans: [
      {
        name: "BASIC",
        monthlyPrice: 29,
        features: [
          "Up to 50 products",
          "Basic templates",
          "2 staff accounts",
          "Email support",
        ],
        highlight: false,
      },
      {
        name: "PRO",
        monthlyPrice: 79,
        annualPrice: 790,
        features: [
          "Unlimited products",
          "Premium templates",
          "5 staff accounts",
          "24/7 support",
          "Abandoned cart recovery",
        ],
        highlight: true,
      },
    ],
  },

  {
    slug: "form-builder",
    title: "Form Builder",
    description:
      "Create powerful forms, surveys, and questionnaires with our intuitive Form Builder. Collect data effortlessly.",
    icon: LayoutTemplate,
    color: "bg-purple-50",
    detailedDescription:
      "Our Form Builder helps you create any type of form with advanced features:",
    features: [
      "Drag-and-drop interface",
      "100+ field types",
      "Conditional logic",
      "File uploads",
      "API integrations",
    ],
    cta: "Build your first form today",
    steps: [
      "Select a template or start blank",
      "Add your form fields",
      "Set up conditional logic",
      "Configure submissions",
      "Publish and share",
    ],
    benefits: [
      "Collect data more efficiently",
      "Integrate with your existing tools",
      "Mobile-responsive forms",
      "Real-time analytics",
    ],
    shortDescription: "Advanced form creation for businesses and teams",
    tags: ["Forms", "Surveys", "Data Collection"],
    results: [
      "75% faster form creation",
      "60% more submissions",
      "4.7/5 user rating",
    ],
    pricingPlans: [
      {
        name: "BASIC",
        monthlyPrice: 19,
        features: [
          "Unlimited forms",
          "100 submissions/month",
          "Basic fields",
          "Email notifications",
        ],
        highlight: false,
      },
    ],
  },
  {
    slug: "landing-page-builder",
    title: "Landing Page Builder",
    description:
      "Create high-converting landing pages without coding. Drag, drop, and publish in minutes.",
    icon: LayoutTemplate,
    color: "bg-green-50",
    detailedDescription:
      "Our Landing Page Builder includes everything for creating effective pages:",
    features: [
      "100+ conversion-optimized templates",
      "A/B testing tools",
      "SEO optimization",
      "Lead capture forms",
      "Integration with marketing tools",
    ],
    cta: "Boost your conversions now",
    steps: [
      "Choose a template",
      "Customize your content",
      "Add conversion elements",
      "Connect your domain",
      "Publish and track results",
    ],
    benefits: [
      "Increase lead generation",
      "No design skills needed",
      "Mobile-responsive pages",
      "Real-time analytics",
    ],
    shortDescription: "Professional landing pages made easy",
    tags: ["Marketing", "Conversion", "Web Design"],
    results: [
      "2x higher conversion rates",
      "90% faster page creation",
      "4.8/5 user satisfaction",
    ],
  },
  {
    slug: "calendar-booking",
    title: "Calendar Booking",
    description:
      "Let clients book appointments 24/7 with your automated scheduling system.",
    icon: Calendar,
    color: "bg-yellow-50",
    detailedDescription:
      "Our Calendar Booking system eliminates scheduling hassles:",
    features: [
      "Sync with Google/Outlook calendars",
      "Automated reminders",
      "Time zone detection",
      "Group scheduling",
      "Payment integration",
    ],
    cta: "Simplify your scheduling",
    steps: [
      "Connect your calendar",
      "Set your availability",
      "Customize booking options",
      "Share your booking link",
      "Manage appointments",
    ],
    benefits: [
      "Reduce no-shows by 80%",
      "Save hours on scheduling",
      "24/7 booking availability",
      "Professional appearance",
    ],
    shortDescription: "Automated appointment scheduling solution",
    tags: ["Scheduling", "Productivity", "Calendar"],
  },
  {
    slug: "crm",
    title: "CRM System",
    description:
      "Manage customer relationships effectively with our all-in-one CRM platform.",
    icon: User,
    color: "bg-red-50",
    detailedDescription: "Our CRM helps you organize and grow your business:",
    features: [
      "Contact management",
      "Sales pipeline",
      "Task automation",
      "Reporting dashboard",
      "Team collaboration",
    ],
    cta: "Transform your customer relationships",
    steps: [
      "Import your contacts",
      "Set up your sales pipeline",
      "Automate follow-ups",
      "Track interactions",
      "Analyze performance",
    ],
    benefits: [
      "30% faster sales cycles",
      "Centralized customer data",
      "Improved team collaboration",
      "Actionable insights",
    ],
    shortDescription: "Complete customer relationship management",
    tags: ["Sales", "Management", "Business"],
  },
  {
    slug: "whatsapp-sender",
    title: "WhatsApp Sender",
    description:
      "Send bulk WhatsApp messages with our powerful messaging platform.",
    icon: MessageCircle,
    color: "bg-green-100",
    detailedDescription: "Our WhatsApp Sender includes:",
    features: [
      "Bulk message sending",
      "Personalized templates",
      "Delivery reports",
      "Contact management",
      "Automated replies",
    ],
    cta: "Start messaging at scale",
    steps: [
      "Connect your WhatsApp account",
      "Import contacts",
      "Create your message template",
      "Schedule your campaign",
      "Analyze results",
    ],
    benefits: [
      "98% open rates",
      "Save hours on communication",
      "Increase engagement",
      "24/7 customer support",
    ],
    shortDescription: "Bulk WhatsApp messaging solution",
    tags: ["Messaging", "Marketing", "Communication"],
  },
  {
    slug: "ad-launcher",
    title: "Ad Launcher",
    description:
      "Create, manage, and optimize ads across multiple platforms from one dashboard.",
    icon: Zap,
    color: "bg-blue-100",
    detailedDescription: "Our Ad Launcher provides:",
    features: [
      "Multi-platform ad creation",
      "Audience targeting",
      "Performance analytics",
      "A/B testing",
      "Automated optimization",
    ],
    cta: "Launch your next campaign",
    steps: [
      "Connect your ad accounts",
      "Set your campaign goals",
      "Create your ad variations",
      "Define your audience",
      "Launch and optimize",
    ],
    benefits: [
      "Manage all ads in one place",
      "50% faster campaign setup",
      "Lower customer acquisition costs",
      "Real-time performance data",
    ],
    shortDescription: "Unified ad management platform",
    tags: ["Advertising", "Marketing", "PPC"],
  },
  {
    slug: "whatsapp-cloud",
    title: "WhatsApp Cloud API",
    description:
      "Integrate WhatsApp messaging directly into your business applications.",
    icon: MessageCircle,
    color: "bg-green-50",
    detailedDescription: "Our WhatsApp Cloud API solution offers:",
    features: [
      "Official WhatsApp API access",
      "High-volume messaging",
      "Message templates",
      "Webhooks",
      "Detailed analytics",
    ],
    cta: "Integrate WhatsApp messaging",
    steps: [
      "Apply for API access",
      "Set up your WhatsApp Business profile",
      "Integrate with our API",
      "Build your messaging flows",
      "Go live with customers",
    ],
    benefits: [
      "Official WhatsApp partnership",
      "99.9% uptime",
      "Enterprise-grade security",
      "Dedicated support",
    ],
    shortDescription: "Enterprise WhatsApp integration",
    tags: ["API", "Messaging", "Integration"],
  },
  {
    slug: "automation-workflow",
    title: "Automation Workflow",
    description:
      "Automate repetitive tasks and business processes with our visual workflow builder.",
    icon: Zap,
    color: "bg-purple-100",
    detailedDescription: "Our Automation Workflow system includes:",
    features: [
      "Visual workflow designer",
      "100+ app integrations",
      "Conditional logic",
      "Error handling",
      "Performance analytics",
    ],
    cta: "Automate your first workflow",
    steps: [
      "Select your trigger",
      "Add workflow steps",
      "Set conditions and filters",
      "Test your workflow",
      "Activate and monitor",
    ],
    benefits: [
      "Save 20+ hours per week",
      "Reduce human error",
      "Scale operations easily",
      "Real-time monitoring",
    ],
    shortDescription: "Business process automation",
    tags: ["Automation", "Productivity", "Integration"],
  },
  {
    slug: "sales-and-finance",
    title: "Sales & Finance",
    description:
      "Complete sales tracking and financial management in one platform.",
    icon: CreditCard,
    color: "bg-blue-50",
    detailedDescription: "Our Sales & Finance system provides:",
    features: [
      "Invoice generation",
      "Expense tracking",
      "Sales reporting",
      "Tax calculations",
      "Payment processing",
    ],
    cta: "Streamline your finances",
    steps: [
      "Connect your bank accounts",
      "Set up your products/services",
      "Create your first invoice",
      "Track expenses",
      "Generate financial reports",
    ],
    benefits: [
      "All financials in one place",
      "Automated tax calculations",
      "Professional invoicing",
      "Real-time cash flow visibility",
    ],
    shortDescription: "Unified sales and finance platform",
    tags: ["Accounting", "Sales", "Finance"],
  },
  {
    slug: "white-label-domain",
    title: "White Label Domain",
    description:
      "Brand our platform as your own with complete white labeling options.",
    icon: Globe,
    color: "bg-gray-100",
    detailedDescription: "Our White Label Domain service includes:",
    features: [
      "Custom domain",
      "Your branding throughout",
      "White label mobile apps",
      "Custom email templates",
      "Dedicated support",
    ],
    cta: "Launch your branded platform",
    steps: [
      "Register your domain",
      "Upload your branding assets",
      "Configure your settings",
      "Test your white label experience",
      "Invite your team",
    ],
    benefits: [
      "Professional branded appearance",
      "Increase customer trust",
      "Stand out from competitors",
      "Enterprise-grade infrastructure",
    ],
    shortDescription: "Complete platform white labeling",
    tags: ["Branding", "Customization", "Enterprise"],
  },
  {
    slug: "sms-automation",
    title: "SMS Automation",
    description: "Automate SMS communications with customers at scale.",
    icon: Smartphone,
    color: "bg-blue-50",
    detailedDescription: "Our SMS Automation platform offers:",
    features: [
      "Bulk SMS sending",
      "Personalized messages",
      "Automated triggers",
      "Two-way messaging",
      "Delivery reports",
    ],
    cta: "Automate your SMS communications",
    steps: [
      "Connect your SMS gateway",
      "Import contacts",
      "Create message templates",
      "Set up automation rules",
      "Launch your campaign",
    ],
    benefits: [
      "95% open rates",
      "Instant communication",
      "Increase engagement",
      "Detailed analytics",
    ],
    shortDescription: "Bulk SMS messaging automation",
    tags: ["SMS", "Marketing", "Automation"],
  },
];
